import {
  Restaurant,
  Category,
  Dish,
  DishTranslation,
  CategoryTranslation,
  Feedback,
  QrCode,
  AnalyticsEvent,
  User,
} from "@/types";

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: "rest_01_pilot_bistro",
    name: "The Olive Grove Bistro",
    slug: "olive-grove",
    logoUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=200&auto=format&fit=crop&q=80",
    description: "Artisanal Mediterranean dining with fresh, seasonal ingredients and rustic wood-fired flavors.",
    address: "104 Heritage Lane, Downtown Arts District",
    phone: "+1 (555) 234-5678",
    email: "contact@olivegrovebistro.com",
    defaultLanguage: "en",
    currency: "USD",
    status: "ACTIVE",
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-01-10T10:00:00Z"),
  },
  {
    id: "rest_02_spice_symphony",
    name: "Spice Symphony",
    slug: "spice-symphony",
    logoUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200&auto=format&fit=crop&q=80",
    description: "Contemporary progressive Indian gastronomy celebrating royal coastal & northern traditions.",
    address: "42 Culinary Row, West End",
    phone: "+1 (555) 987-6543",
    email: "reservations@spicesymphony.com",
    defaultLanguage: "en",
    currency: "USD",
    status: "ACTIVE",
    createdAt: new Date("2025-01-15T12:00:00Z"),
    updatedAt: new Date("2025-01-15T12:00:00Z"),
  },
];

export const MOCK_USERS: User[] = [
  {
    id: "usr_mock_admin_01",
    restaurantId: "rest_01_pilot_bistro",
    name: "Elena Rostova",
    email: "manager@olivegrovebistro.com",
    passwordHash: "$2b$10$e8w.mockhashedpasswordforpilotdevs",
    role: "RESTAURANT_ADMIN",
    status: "ACTIVE",
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-01-10T10:00:00Z"),
  },
  {
    id: "usr_mock_superadmin_01",
    restaurantId: null,
    name: "SilvyOS System Admin",
    email: "admin@silvyos.com",
    passwordHash: "$2b$10$e8w.mockhashedpasswordforsuperadmin",
    role: "SUPER_ADMIN",
    status: "ACTIVE",
    createdAt: new Date("2025-01-01T00:00:00Z"),
    updatedAt: new Date("2025-01-01T00:00:00Z"),
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat_01_starters",
    restaurantId: "rest_01_pilot_bistro",
    name: "Starters & Small Plates",
    description: "Light, vibrant bites to ignite your palate",
    displayOrder: 1,
    isActive: true,
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-01-10T10:00:00Z"),
  },
  {
    id: "cat_02_mains",
    restaurantId: "rest_01_pilot_bistro",
    name: "Wood-Fired Mains",
    description: "Hearty main courses crafted in our artisanal stone oven",
    displayOrder: 2,
    isActive: true,
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-01-10T10:00:00Z"),
  },
  {
    id: "cat_03_desserts",
    restaurantId: "rest_01_pilot_bistro",
    name: "Sweet Finishes",
    description: "Decadent desserts made in-house daily",
    displayOrder: 3,
    isActive: true,
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-01-10T10:00:00Z"),
  },
];

export const MOCK_CATEGORY_TRANSLATIONS: CategoryTranslation[] = [
  {
    id: "ct_01_starters_hi",
    categoryId: "cat_01_starters",
    languageCode: "hi",
    name: "शुरुआती व्यंजन (Starters)",
    description: "स्वादिष्ट और हल्के व्यंजन",
  },
  {
    id: "ct_02_starters_mr",
    categoryId: "cat_01_starters",
    languageCode: "mr",
    name: "सुरुवातीचे पदार्थ (Starters)",
    description: "हलके आणि चवदार पदार्थ",
  },
];

export const MOCK_DISHES: Dish[] = [
  {
    id: "dish_01_bruschetta",
    restaurantId: "rest_01_pilot_bistro",
    categoryId: "cat_01_starters",
    name: "Heirloom Tomato Bruschetta",
    description: "Grilled sourdough toast infused with garlic, topped with marinated heirloom cherry tomatoes, fresh basil, and aged balsamic glaze.",
    price: 12.5,
    portion: "3 Pieces (220g)",
    ingredients: "Rustic Sourdough, Heirloom Tomatoes, Basil, Extra Virgin Olive Oil, Garlic, Balsamic Reduction",
    allergens: "Gluten (Wheat)",
    dietaryType: "VEGAN",
    imageUrl: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800&auto=format&fit=crop&q=80",
    model3dUrl: "/models/bruschetta.glb",
    arEnabled: true,
    isAvailable: true,
    displayOrder: 1,
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-01-10T10:00:00Z"),
  },
  {
    id: "dish_02_calamari",
    restaurantId: "rest_01_pilot_bistro",
    categoryId: "cat_01_starters",
    name: "Crispy Herb Calamari",
    description: "Tender flash-fried squid dusted with wild oregano, sea salt, served with lemon-garlic aioli.",
    price: 16.0,
    portion: "Serves 1-2 (250g)",
    ingredients: "Calamari, Wild Oregano, Garlic Aioli, Lemon, Smoked Paprika",
    allergens: "Molluscs, Eggs, Gluten",
    dietaryType: "NON_VEGETARIAN",
    imageUrl: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80",
    model3dUrl: null,
    arEnabled: false,
    isAvailable: true,
    displayOrder: 2,
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-01-10T10:00:00Z"),
  },
  {
    id: "dish_03_salmon",
    restaurantId: "rest_01_pilot_bistro",
    categoryId: "cat_02_mains",
    name: "Pan-Seared Atlantic Salmon",
    description: "Crispy skin salmon filet rested over asparagus risotto and drizzled with saffron-dill velouté.",
    price: 28.0,
    portion: "Full Entrée (340g)",
    ingredients: "Atlantic Salmon, Arborio Rice, Asparagus, Saffron, White Wine, Dill",
    allergens: "Fish, Dairy",
    dietaryType: "NON_VEGETARIAN",
    imageUrl: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop&q=80",
    model3dUrl: "/models/salmon_plate.glb",
    arEnabled: true,
    isAvailable: true,
    displayOrder: 1,
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-01-10T10:00:00Z"),
  },
  {
    id: "dish_04_tiramisu",
    restaurantId: "rest_01_pilot_bistro",
    categoryId: "cat_03_desserts",
    name: "Classic Espresso Tiramisu",
    description: "Layered Savoiardi soaked in dark roast espresso and Marsala, whipped mascarpone cream, and Dutch cocoa dusting.",
    price: 9.5,
    portion: "Single Portion (180g)",
    ingredients: "Mascarpone, Espresso, Ladyfingers, Marsala, Cocoa Powder, Eggs",
    allergens: "Dairy, Eggs, Gluten",
    dietaryType: "VEGETARIAN",
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop&q=80",
    model3dUrl: null,
    arEnabled: false,
    isAvailable: true,
    displayOrder: 1,
    createdAt: new Date("2025-01-10T10:00:00Z"),
    updatedAt: new Date("2025-01-10T10:00:00Z"),
  },
];

export const MOCK_DISH_TRANSLATIONS: DishTranslation[] = [
  {
    id: "dt_01_bruschetta_hi",
    dishId: "dish_01_bruschetta",
    languageCode: "hi",
    name: "टमाटर ब्रुशेटा (Tomato Bruschetta)",
    description: "लहसुन और जैतून के तेल में भुना हुआ ब्रेड, ताजे टमाटर और तुलसी के साथ।",
    ingredients: "खमीरयुक्त ब्रेड, टमाटर, तुलसी, जैतून का तेल, लहसुन",
    allergens: "ग्लूटेन (गेहूं)",
    portion: "3 टुकड़े (220 ग्राम)",
  },
  {
    id: "dt_01_bruschetta_mr",
    dishId: "dish_01_bruschetta",
    languageCode: "mr",
    name: "टोमॅटो ब्रुशेटा (Tomato Bruschetta)",
    description: "लसूण आणि ऑलिव्ह ऑइलमध्ये भाजलेला ब्रेड, ताजे टोमॅटो आणि तुळशीच्या पानांसह.",
    ingredients: "ब्रेड, टोमॅटो, तुळस, ऑलिव्ह ऑइल, लसूण",
    allergens: "ग्लूटेन (गहू)",
    portion: "3 तुकडे (220 ग्रॅम)",
  },
];

export const MOCK_FEEDBACK: Feedback[] = [
  {
    id: "fb_01",
    restaurantId: "rest_01_pilot_bistro",
    dishId: "dish_01_bruschetta",
    rating: 5,
    comment: "The tomatoes tasted straight from the garden! Crisp bread was perfect.",
    languageCode: "en",
    createdAt: new Date("2025-01-20T14:30:00Z"),
  },
  {
    id: "fb_02",
    restaurantId: "rest_01_pilot_bistro",
    dishId: "dish_03_salmon",
    rating: 4,
    comment: "Salmon was cooked to perfection. Loved checking out the AR model before ordering!",
    languageCode: "en",
    createdAt: new Date("2025-01-21T18:15:00Z"),
  },
];

export const MOCK_QR_CODES: QrCode[] = [
  {
    id: "qr_01_main_tables",
    restaurantId: "rest_01_pilot_bistro",
    identifier: "OG-TABLE-ALL",
    destinationUrl: "https://menu.silvyos.com/r/olive-grove",
    status: "ACTIVE",
    createdAt: new Date("2025-01-10T10:00:00Z"),
  },
];

export const MOCK_ANALYTICS_EVENTS: AnalyticsEvent[] = [
  {
    id: "ev_01",
    restaurantId: "rest_01_pilot_bistro",
    eventType: "menu_view",
    sessionId: "sess_mock_101",
    languageCode: "en",
    createdAt: new Date("2025-01-22T11:00:00Z"),
  },
  {
    id: "ev_02",
    restaurantId: "rest_01_pilot_bistro",
    categoryId: "cat_01_starters",
    eventType: "category_view",
    sessionId: "sess_mock_101",
    languageCode: "en",
    createdAt: new Date("2025-01-22T11:01:00Z"),
  },
  {
    id: "ev_03",
    restaurantId: "rest_01_pilot_bistro",
    dishId: "dish_01_bruschetta",
    eventType: "dish_view",
    sessionId: "sess_mock_101",
    languageCode: "en",
    createdAt: new Date("2025-01-22T11:01:30Z"),
  },
  {
    id: "ev_04",
    restaurantId: "rest_01_pilot_bistro",
    dishId: "dish_01_bruschetta",
    eventType: "ar_launch",
    sessionId: "sess_mock_101",
    languageCode: "en",
    createdAt: new Date("2025-01-22T11:02:00Z"),
  },
];
